bin/testCircle:src/testCircle.cpp src/Circle.cpp src/Shape.cpp src/Point2D.cpp
	
	g++ -c src/Point2D.cpp -o bin/Point2D.o
	g++ -c src/Shape.cpp -o bin/Shape.o
	g++ -c src/Circle.cpp -o bin/Circle.o
	g++ -c src/testCircle.cpp -o bin/testCircle.o
	g++ -o bin/testCircle bin/testCircle.o bin/Circle.o bin/Shape.o bin/Point2D.o


